download:
	mkdir -p streams
	cd streams && curl -O https://raw.githubusercontent.com/docker/cli/19.03/cli/streams/in.go
	cd streams && curl -O https://raw.githubusercontent.com/docker/cli/19.03/cli/streams/out.go
	cd streams && curl -O https://raw.githubusercontent.com/docker/cli/19.03/cli/streams/stream.go

	mkdir -p hijack
	cd hijack && curl -O https://raw.githubusercontent.com/docker/cli/19.03/cli/command/container/hijack.go
